<?php
return array('1'=>array(
		'<option value="00054">CITIC Bank</option>',
		'<option value="00083">Bank of China</option>',
		'<option value="00017">Agricultural Bank of China</option>',
		'<option value="00015">China Construction Bank</option>',
		'<option value="00004">ICBC</option>',
		'<option value="00086">Zheshang Bank</option>',
		'<option value="00021">Merchant Bank of China</option>',
		'<option value="00051">Postal Savings</option>',
		'<option value="00016">Industrial Bank</option>',
		'<option value="00023">Shenzhen Development Bank</option>',
		'<option value="00084">Bank of Shanghai</option>',
		'<option value="00032">Pudong Development Bank</option>',
		'<option value="00087">Ping a bank</option>',
		'<option value="00085">Bank of Ningbo</option>',
		'<option value="00194">Bank of Nanjing</option>',
		'<option value="00013">Minsheng Bank</option>',
		'<option value="00005">Bank of Communications</option>',
		'<option value="00041">Hua Xia Bank</option>',
		'<option value="00149">Bank of Hebei</option>',
		'<option value="00081">Hangzhou Bank</option>',
		'<option value="00052">Guangfa Bank</option>',
		'<option value="00057">Everbright Bank</option>',
		'<option value="00096">BEA</option>',
		'<option value="00095">Bohai Bank</option>',
		'<option value="00050">Bank of Beijing</option>',
		'<option value="00056">Peking Rural Commercial Bank</option>'),
     '2'=>array(
		'<opción valor="ICBC">ICBC</option>',
		'<option value="CCB">Construction Bench</option>',
		'<option value="ABC">Agricultural Bank</option>',
		'<option value="CMB">Merchant Bank of China</option>',
		'<option value="COMM">Bank of Communications</option>',
		'<option value="BOC">Bank of China</option>',
		'<option value="CEB">Everbright Bank</option>',
		'<option value="CMBC">Minsheng Bank</option>',
		'<option value="CITIC">CITIC Bank</option>',
		'<option value="CIB">Industrial Bank</option>',
		'<option value="GDB">Guangdong Development Bank</option>',
		'<option value="SPDB">Pudong Development Bank</option>',
		'<option value="SZPAB">Ping a bank</option>',
		'<option value="HXB">Hua Xia Bank</option>',
		'<option value="NBCB">Bank of Ningbo</option>',
		'<option value="BCCB">Bank of Beijing</option>',
		'<option value="HKBEA">Bank of East Asia</option>',
		'<option value="BOS">Shanghai Bank</option>',
		'<option value="PSBC">China Post Savings Bank</option>',
		'<option value="NJCB">Nanjing Bank</option>',
		'<option value="CBHB">Bohai Bank</option>',
		'<option value="BOCD">Chengdu Bank</option>',
		'<option value="SHRCB">Shanghai Rural Commercial Bank</option>',
		'<option value="GNXS">Guangzhou Rural Commercial Bank</option>',
		'<option value="HKBCHINA">Hankou Bank</option>',
		'<option value="SXJS">Shanxi Merchant Bank</option>',
		'<option value="ZHNX">Zhuhai Rural Commercial Bank</option>',
		'<option value="WZCB">Wenzhou Bank</option>',
		'<option value="YDXH">Yaodu Rural Commercial Bank</option>',
		'<option value="SDE">Shunde Rural Commercial Bank</option>',),
	'3'=>array(
         
        '<option value="967">ICBC</option>',
		'<option value="965">China Construction Bank</option>',
		'<option value="963">Bank of China</option>',
		'<option value="986">Everbright Bank</option>',
		'<option value="971">Postal Savings Fund</option>',
		'<option value="992">Bank of Shanghai</option>',
		'<option value="985">Guangfa Bank</option>',
		'<option value="970">Merchant Bank of China</option>',
		'<option value="991">Hua Xia Bank</option>',
		'<opción valor="962">CITIC Bank</option>',
		'<option value="972">Industrial Bank</option>',
		'<option value="980">Minsheng Bank of China</option>',
		'<option value="989">Bank of Beijing</option>',
		'<option value="990">Ping a bank</option>',
      
       
	),
	

);


/**

		'<option value="DXGK">电信国卡</option>',
		'<option value="LTYKT">联通一卡充</option>',
		'<option value="YDSZX">移动神州行</option>',
		'<option value="GYYKT">光宇一卡通</option>',
		'<option value="JWYKT">骏网一卡通</option>',
		'<option value="JYYKT">久游一卡通</option>',
		'<option value="QBCZK">QQ币充值卡</option>',
		'<option value="SDYKT">盛大一卡通</option>',
		'<option value="SHYKT">搜狐一卡通</option>',
		'<option value="SFYKT">盛付通一卡通</option>',
		'<option value="SHYKT">搜狐一卡通</option>',
		'<option value="THYKT">天宏一卡通</option>',
		'<option value="TXYKT">天下一卡通</option>',
		'<option value="TXYKTZX">天下一卡通专项</option>',
		'<option value="WMYKT">完美一卡通</option>',
		'<option value="WYYKT">网易一卡通</option>',
		'<option value="ZTYKT">征途一卡通</option>',
		'<option value="ZYYKT ">纵游一卡通</option>',



*/
?>