<?php

$data = [
    1 => [
        ['value' => "00054",  'name' => 'CITIC Bank'],
        ['value' => "00083",  'name' => 'Bank of China'],
        ['value' => "00017",  'name' => 'Agricultural Bank of China'],
        ['value' => "00015",  'name' => 'China Construction Bank'],
        ['value' => "00004",  'name' => 'ICBC'],
        ['value' => "00086",  'name' => 'Zheshang Bank'],
        ['value' => "00021",  'name' => 'Merchant Bank of China'],
        ['value' => "00051",  'name' => 'postal savings'],
        ['value' => "00016",  'name' => 'Industrial Bank'],
        ['value' => "00023",  'name' => 'Shenzhen Development Bank'],
        ['value' => "00084",  'name' => 'Shanghai Bank'],
        ['value' => "00032",  'name' => 'Pudong Development Bank'],
        ['value' => "00087",  'name' => 'Ping a bank'],
        ['value' => "00085",  'name' => 'Ningbo Bank'],
        ['value' => "00194",  'name' => 'Nanjing Bank'],
        ['value' => "00013",  'name' => 'Minsheng Bank'],
        ['value' => "00005",  'name' => 'Bank of Communications'],
        ['value' => "00041",  'name' => 'HSBC Bank'],
        ['value' => "00149",  'name' => 'Hebei Bank'],
        ['value' => "00081",  'name' => 'Hangzhou Bank'],
        ['value' => "00052",  'name' => 'Guangfa Bank'],
        ['value' => "00057",  'name' => 'Always Brilliant Bench'],
        ['value' => "00096",  'name' => 'Bank of East Asia'],
        ['value' => "00095",  'name' => 'Bohai Bank'],
        ['value' => "00050",  'name' => 'Bank of Peking'],
        ['value' => "00056",  'name' => 'Beijing Rural Commercial Bank'],
    ],
    2 => [
        ['value' => "ICBC", 'name' => 'ICBC'],
        ['value' => "CCB",  'name' => 'Construction Bank'],
        ['value' => "ABC",  'name' => 'ABC'],
        ['value' => "CMB",  'name' => 'Merchant Bank of China'],
        ['value' => "COMM", 'name' => 'Bank of Communications'],
        ['value' => "BOC",  'name' => 'Bank of China'],
        ['value' => "CEB",  'name' => 'Always Brilliant Bench'],
        ['value' => "CMBC", 'name' => 'Minsheng Bank'],
        ['value' => "CITIC",'name' => 'CITIC Bank'],
        ['value' => "CIB",  'name' => 'Industrial Bank'],
        ['value' => "GDB",  'name' => 'Guangdong Development Bank'],
        ['value' => "SPDB", 'name' => 'Pudong Development Bank'],
        ['value' => "SZPAB",'name' => 'Ping a bank'],
        ['value' => "HXB",  'name' => 'HSBC Bank'],
        ['value' => "NBCB", 'name' => 'Ningbo Bank'],
        ['value' => "BCCB", 'name' => 'Bank of Peking'],
        ['value' => "HKBEA",'name' => 'Bank of East Asia'],
        ['value' => "BOS",  'name' => 'Shanghai Bank'],
        ['value' => "PSBC", 'name' => 'Postal Savings Bank of China'],
        ['value' => "NJCB", 'name' => 'Nanjing Bank'],
        ['value' => "CBHB", 'name' => 'Bohai Bank'],
        ['value' => "BOCD", 'name' => 'Chengdu Bank'],
        ['value' => "SHRCB",'name' => 'Shanghai Rural Commercial Bank'],
        ['value' => "GNXS", 'name' => 'Guangzhou Rural Commercial Bank'],
        ['value' => "HKBCHINA",'name' => 'Hankou Bank'],
        ['value' => "SXJS", 'name' => 'Jin Merchant Bank'],
        ['value' => "ZHNX", 'name' => 'Zhuhai Rural Commercial Bank'],
        ['value' => "WZCB", 'name' => 'Wenzhou Bank'],
        ['value' => "YDXH", 'name' => 'Yaodu Rural Commercial Bank'],
        ['value' => "SDE",  'name' => 'Shunde Rural Commercial Bank'],
    ],
    3 => [
        ['value' => "967", 'name' => 'ICBC'],
        ['value' => "965", 'name' => 'China Construction Bank'],
        ['value' => "963", 'name' => 'Bank of China'],
        ['value' => "986", 'name' => 'always bright bench'],
        ['value' => "971", 'name' => 'Postal Savings Bank'],
        ['value' => "992", 'name' => 'Shanghai Bank'],
        ['value' => "985", 'name' => 'Guangfa Bank of China'],
        ['value' => "970", 'name' => 'Merchant Bank of China'],
        ['value' => "991", 'name' => 'HSBC Bank'],
        ['value' => "962", 'name' => 'CITIC Bank'],
        ['value' => "972", 'name' => 'Industrial Bank'],
        ['value' => "980", 'name' => 'Minsheng Bank of China'],
        ['value' => "989", 'name' => 'Bank of Peking'],
        ['value' => "990", 'name' => 'Ping a bank'],
    ]
];


return $data;
?>